config/routes.rb
Rails.application.routes.draw do
  root :to => 'products#index'
  resources :products do
    resources :reviews, except: [:destroy, :update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy
  # dry code a bit here?
  validates :name, presence: true
  validates :cost, presence: true
  validates :country_of_origin, presence: true

  before_save(:titleize_product_name)

  private
    def titleize_product_name
      self.name = self.name.titleize
    end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product

  # dry code a bit here?
  validates :author, presence: true
  validates :rating, presence: true
  validates :content_body, presence: true

  before_save(:titleize_reviewer_name)

  private
    def titleize_reviewer_name
      self.author = self.author.titleize
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
    render :index
  end

  def new
    @product = Product.new
    render :new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
      flash[:notice] = "Product saved!"
    else
      flash[:alert] = "Product not saved"
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    render :edit
  end

  def show
    @product = Product.find(params[:id])
    @reviews = @product.reviews
    render :show
  end

  def update
    @product= Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
      flash[:notice] = "Product updated!"
    else
      flash[:alert] = "Product not updated"
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.reviews.each do |review|
      review.destroy
    end
    @product.destroy
    redirect_to products_path
  end

  private
    def product_params
      params.require(:product).permit(:name, :cost, :country_of_origin)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    render :new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :show
  end

  private
    def review_params
      params.require(:review).permit(:name, :project_id, :rating, :content_body)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarioProducts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!--- javascript_include_tag 'application', 'data-turbolinks-track': 'reload' --->
  </head>

  <body>
    <p><a href="/">Home</a></p>
    
    <%= flash[:alert] %>
    <%= flash[:notice] %>

    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :cost %>
  <%= f.text_field :cost %>
  <%= f.label :country_of_origin %>
  <%= f.text_field :country_of_origin %>
  <%= f.submit  %>
<% end %>

app/views/products/index.html.erb
<h1>Products</h1>

<% if @products.any? %>
<ul>
  <% @products.each do |product| %>
  <li><%= link_to product.name, product_path(product) %></li>
  <% end %>
</ul>
<% else %>
<p>There are no products yet.</p>
<% end %>

<p><%= link_to "Add Product", new_product_path %></p>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :cost %>
  <%= f.text_field :cost %>
  <%= f.label :country_of_origin %>
  <%= f.text_field :country_of_origin %>
  <%= f.submit  %>
<% end %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>

<ul>
  <% @reviews.each do |review| %>
  <li><%= link_to review.author, product_review_path(@product, review) %></li>
  <li><%= review.content_body %></li>
  <% end %>
</ul>

<p><%= link_to "Add Review", new_product_review_path(@product) %></p>
<p><%= link_to "Edit", edit_product_path(@product) %></p>
<p><%= link_to "Delete", product_path(@product),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>

<p><%= link_to "Return to products", products_path %></p>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render "layouts/errors", :object => @review %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :rating %>
  <%= f.text_field :rating %>
  <%= f.label :content_body %>
  <%= f.text_area :content_body %>
  <%= f.submit  %>
<% end %>

app/views/reviews/show.html.erb
<h1><%= @review.author %></h1>

<p><%= @review.content_body %></p>

<p><%= link_to "Return to products", products_path %></p>